=== WPS/ts-archlint/doc/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "archlint://archlint.schema.json",
  "title": "Schema for Archlint Architecture descriptions",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9-\\_]+$"
    },
    "exclude": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "additionalItems": false
    },
    "failOnUnassigned": {
      "type": "boolean"
    },
    "artifacts": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ArtifactDescription"
      },
      "additionalItems": false
    }
  },
  "additionalProperties": false,
  "required": [
    "name"
  ],
  "definitions": {
    "ArtifactDescription": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[a-zA-Z0-9-_]+$"
        },
        "mayUseAllBelow": {
          "type": "boolean"
        },
        "mayBeUsedFromAllAbove": {
          "type": "boolean"
        },
        "include": {
          "$ref": "#/definitions/StringOrStringArray"
        },
        "mayUse": {
          "$ref": "#/definitions/StringOrStringArray"
        },
        "children": {
          "type": "array",
          "additionalItems": false,
          "items": {
            "$ref": "#/definitions/ArtifactDescription"
          }
        },
        "additionalProperties": false
      },
      "required": [
        "name"
      ]
    },
    "ArtifactNames": {
      "oneOf": [
        {
          "$ref": "#/definitions/ArtifactName"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ArtifactName"
          },
          "additionalItems": false
        }
      ]
    },
    "ArtifactName": {
      "type": "string",
      "pattern": "^([a-zA-Z0-9-_]+)(\\.([a-zA-Z0-9-_]+))*$"
    },
    "StringOrStringArray": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalItems": false
        }
      ]
    }
  }
}

=== WPS/ts-archlint/.archlint/domain.arch.json
{
  "$schema": "../src/schema.json",
  "name": "domain-layers",
  "exclude": [
    "**.spec.ts"
  ],
  "failOnUnassigned": true,
  "artifacts": [
    {
      "name": "cli",
      "include": [
        "cli/**",
        "index.ts"
      ],
      "mayUseAllBelow": true
    },
    {
      "name": "report",
      "include": [
        "report/**"
      ],
      "mayUse": [
        "check",
        "assign"
      ]
    },
    {
      "name": "check",
      "include": [
        "check/**"
      ],
      "mayUse": [
        "describe",
        "assign",
        "parse"
      ]
    },
    {
      "name": "assign",
      "include": [
        "assign/**"
      ],
      "mayUse": [
        "describe",
        "parse"
      ]
    },
    {
      "name": "describe",
      "include": [
        "describe/**"
      ],
      "mayUse": [
        "parse"
      ]
    },
    {
      "name": "parse",
      "include": [
        "parse/**"
      ]
    },
    {
      "name": "common",
      "include": [
        "common/**"
      ],
      "mayBeUsedFromAllAbove": true
    },
    {
      "name": "external",
      "include": "node_modules/**",
      "mayBeUsedFromAllAbove": true
    }
  ]
}
